# Generated by Django 3.2.23 on 2023-11-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
