# Generated by Django 3.2.23 on 2023-12-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0004_auto_20231130_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
