# Generated by Django 3.2.23 on 2024-02-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0005_auto_20231201_0052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
