# Generated by Django 3.2.23 on 2024-02-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_auto_20231205_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='newsletter_subscribed',
        ),
    ]
